# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "xdelta-merger"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pawel Barcik"]
  s.date = "2013-06-03"
  s.description = ""
  s.email = "pawel.barcik@gmail.com"
  s.executables = ["xdelta_merger"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/xdelta_merger",
    "lib/.gitkeep",
    "lib/xdelta-merger/entities.rb",
    "lib/xdelta-merger/entities/files.rb",
    "lib/xdelta-merger/entities/files/basic_file.rb",
    "lib/xdelta-merger/entities/files/basic_file_creator.rb",
    "lib/xdelta-merger/entities/files/contents.rb",
    "lib/xdelta-merger/entities/files/contents/memory_based_content.rb",
    "lib/xdelta-merger/entities/files/versioned_file.rb",
    "lib/xdelta-merger/entities/files/versioned_file_creator.rb",
    "lib/xdelta-merger/merger.rb",
    "lib/xdelta-merger/patcher.rb",
    "lib/xdelta_merger.rb",
    "spec/fixtures.rb",
    "spec/fixtures/file_fixtures.rb",
    "spec/fixtures/file_list.yml",
    "spec/integration/merger_spec.rb",
    "spec/lib/xdelta-merger/entities/contents/memory_based_content_spec.rb",
    "spec/lib/xdelta-merger/entities/files/basic_file_creator_spec.rb",
    "spec/lib/xdelta-merger/entities/files/basic_file_spec.rb",
    "spec/lib/xdelta-merger/entities/files/versioned_file_creator_spec.rb",
    "spec/lib/xdelta-merger/entities/files/versioned_file_spec.rb",
    "spec/lib/xdelta-merger/merger_spec.rb",
    "spec/lib/xdelta-merger/patcher_spec.rb",
    "spec/lib/xdelta_merger_spec.rb",
    "spec/spec_helper.rb",
    "xdelta-merger.gemspec"
  ]
  s.homepage = "http://github.com/pbc/xdelta-merger"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.25"
  s.summary = ""

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xdelta-merger>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<xdelta-merger>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<xdelta-merger>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

